package exception;

public class Ex03 {

	public static void printArr(int[] arr) {
		for(int a : arr)
			System.out.print(a + " ");
		System.out.println();
		
		throw new ArrayIndexOutOfBoundsException("배열 예외"); // to intentionally cause / create an Exception
	}
	
	public static void main(String[] args) {
		int[] arr = new int[] {10, 20, 30, 40, 50};
		
		try {
			printArr(arr);
		}
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("무슨 예외인고?");
			System.out.println(e.getMessage());
		}
	}

}
