package exception;

public class Ex04 {

	public static void count() throws InterruptedException {
		for(int i = 0; i < 10; i++) {
			System.out.println(i + "ÃÊ~");
			Thread.sleep(1000);
		}
	}
	
	public static void main(String[] args) throws InterruptedException {	// throws EXCEPCTION to pass the responsibility to whoever called this method

		count();

	}

}
